---
title: ""
---

<br>

I am an associate professor at the Department of Economics at University of Bristol. My academic interests are in theoretical and applied microeconometrics.

### Working papers

> [Binarization for panel models with fixed effects](./Botosaru Muris - Binarization [2018].pdf)
> <small>with Irene Botosaru</small>
> <small>Updated: June, 2018. Submitted.</small>

> [Estimation of a factor-augmented linear panel data model with applications using student achievement data](./hlm27.pdf)
> <small>with Matthew Harding and Carlos Lamarche</small> 
> <small>Updated: July 2019. Submitted.</small>

> [DICE simplified](./ILMM2019-DICE-simplified.pdf)
> <small>with Masako Ikefuji, Roger Laeven and Jan Magnus </small> 
> <small>Updated: July 2019. Submitted.</small>



### Publications

> [Interval censored regression with fixed effects](./AM2019.pdf)
> <small>with Jason Abrevaya</small>
> <small><b>Journal of Applied Econometrics</b>, forthcoming.</small>
> <small>[data and code](https://github.com/chrismuris/IntervalFixedEffects)</small>

> [Efficient GMM estimation with incomplete data](./M2019-incompleteData.pdf)
> <small><b>Review of Economics and Statistics</b>, forthcoming.</small>
> <small>[R code](https://doi.org/10.7910/DVN/ZKQPK7)</small>

> [Expected utility and catastrophic risk in a stochastic economy-climate model](./ILMM2019-catastrophe.pdf)
> <small>with Masako Ikefuji, Roger Laeven and Jan Magnus </small> 
> <small><b>Journal of Econometrics</b>, forthcoming.</small>

> [Estimation in the fixed effects ordered logit model](http://www.mitpressjournals.org/doi/pdf/10.1162/REST_a_00617) 
> <small><b>Review of Economics and Statistics</b>, 99 (3), 465-477, 2017. </small>
> <small>[slides](feol-slides-201604.pdf), [Stata code](http://dx.doi.org/10.7910/DVN/IUJ3VZ)</small>

> [The trade-off between income inequality and carbon dioxide emissions](https://doi.org/10.1016/j.ecolecon.2017.06.034)
> <small>with Nicole Grunewald, Stephan Klasen, and Inmaculada Martinez-Zarzoso </small>
> <small><b>Ecological Economics</b>, 142, 249-256, 2017.</small>

> [Model averaging in semiparametric estimation of treatment effects](http://dx.doi.org/10.1016/j.jeconom.2016.03.002)
> <small>with Toru Kitagawa </small> 
> <small><b>Journal of Econometrics</b>, 193 (1), 271-289, 2016.</small>
> <small>[slides](KM2013-slides.pdf), [R code](KM-code.zip) </small>

> [Expected utility and catastrophic consumption risk](http://dx.doi.org/10.1016/j.insmatheco.2015.06.007)
> <small>with Masako Ikefuji, Roger Laeven and Jan Magnus </small> 
> <small><b>Insurance: Mathematics and Economics</b>, 64, 306-312, 2015.</small>

> [Do climate variations explain bilateral migration? A gravity model analysis](http://www.izajom.com/content/4/1/3) 
> <small>with Andreas Backhaus and Inmaculada Martinez-Zarzoso </small> 
> <small><b>IZA Journal of Migration</b>, 4:3, 2015.</small>

> [Pareto utility](http://dx.doi.org/10.1007/s11238-012-9293-8)
> <small>with Masako Ikefuji, Roger Laeven and Jan Magnus</small>
> <small><b>Theory and Decision</b>, 75, 43-57, 2013.</small>

> [Statistical climate-change scenarios](http://www.jenvstat.org/v05/i04)
> <small>with Jan Magnus, Bertrand Melenberg and Martin Wild</small>
> <small><b>Journal of Environmental Statistics</b>, 5 (4), 1-18, 2013.</small>

> [Global warming and local dimming: the statistical evidence](http://dx.doi.org/10.1198/jasa.2011.ap09508) 
> <small>with Jan Magnus and Bertrand Melenberg </small>
> <small><b>Journal of the American Statistical Association</b>, 106, 467-468, 2011.</small>
> <small>with discussion and [rejoinder](http://dx.doi.org/10.1198/jasa.2011.ap11319)</small>
> <small>[slides](MMM2010_slides.pdf)</small>

> [Specification of variance matrices for panel data models](http://dx.doi.org/10.1017/S0266466609090756)
> <small>with Jan Magnus</small>
> <small><b>Econometric Theory</b>, 26, 301-310, 2010.</small>
